services:
  app:
    build: .
    container_name: app_container
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3005:3005"
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    container_name: db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: coordinadora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network: